export const LOAD_PROCCERSOR_BEGIN = 'LOAD_PROCCERSOR_BEGIN';
export const LOAD_PROCCERSOR_SUCCESS = 'LOAD_PROCCERSOR_SUCCESS';
export const LOAD_PROCCERSOR_FAILURE = 'LOAD_PROCCERSOR_FAILURE';

export const LOAD_MOTHERBOARD_BEGIN = 'LOAD_MOTHERBOARD_BEGIN';
export const LOAD_MOTHERBOARD_SUCCESS = 'LOAD_MOTHERBOARD_SUCCESS';
export const LOAD_MOTHERBOARD_FAILURE = 'LOAD_MOTHERBOARD_FAILURE';

export const LOAD_GPU_BEGIN = 'LOAD_GPU_BEGIN';
export const LOAD_GPU_SUCCESS = 'LOAD_GPU_SUCCESS';
export const LOAD_GPU_FAILURE = 'LOAD_GPU_FAILURE';

export const LOAD_RESULT_BEGIN = 'LOAD_RESULT_BEGIN';
export const LOAD_RESULT_SUCCESS = 'LOAD_RESULT_SUCCESS';
export const LOAD_RESULT_FAILURE = 'LOAD_RESULT_FAILURE';

export const LOAD_FILTER_BEGIN = 'LOAD_FILTER_BEGIN';
export const LOAD_FILTER_SUCCESS = 'LOAD_FILTER_SUCCESS';
export const LOAD_FILTER_FAILURE = 'LOAD_FILTER_FAILURE';